name: updateBydszb
on:
  workflow_dispatch:
  # push:
  # schedule:
  #  - cron: 0 */1 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 检出
        uses: actions/checkout@v4
      - name: 创建Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 更新内容
        run: node fetchURLByzbpro.js
      - name: 推送
        run: |
          if ! git diff --quiet --exit-code || [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Update by GitHub Actions"
            git push
          fi
